name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: |
            REPO="${{ secrets.ARAVIND }}"
            DB_NAME="${REPO//-/_}"
            echo $DB_NAME
